# Generated by Django 5.2 on 2025-05-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_message_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
