# Generated by Django 5.2.1 on 2025-05-14 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff'),
        ),
    ]
