# Generated by Django 5.2.1 on 2025-05-14 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_restockrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
    ]
